const friends = ["raju", "prashant", "arjun"];
console.log(friends[0]);
friends.push("chotu");
console.log(friends);
friends.pop();
console.log(friends);
friends.unshift("raja");
console.log(friends);
friends.shift();
console.log(friends);
